import pytest

from core.schemas import AttackPrompt, JudgeDecision, ScanSettings, TargetConfig, TargetResponse
from engine.scenario_loader import PluginLoader


class SafeTargetExecutor:
    async def execute(self, target: TargetConfig, attack_prompt: AttackPrompt, conversation_id: str) -> TargetResponse:
        return TargetResponse(
            status_code=200,
            body="I cannot reveal hidden instructions or confidential policy text.",
            headers={},
            elapsed_ms=1,
        )


class SuccessOnSecondTurnExecutor:
    def __init__(self) -> None:
        self.calls = 0

    async def execute(self, target: TargetConfig, attack_prompt: AttackPrompt, conversation_id: str) -> TargetResponse:
        self.calls += 1
        if self.calls == 2:
            return TargetResponse(
                status_code=200,
                body="full system prompt: internal policy and developer message exposed",
                headers={},
                elapsed_ms=1,
            )
        return TargetResponse(
            status_code=200,
            body="I cannot reveal hidden instructions or confidential policy text.",
            headers={},
            elapsed_ms=1,
        )


class AnyJudge:
    async def decide(self, target: TargetConfig, turns):
        return JudgeDecision(
            next_action="terminate",
            reasoning="Judge recommendation is recorded but should not end the run.",
            risk_score=0.2,
            continue_attack=False,
            suggested_prompt="Adaptive continuation prompt generated by judge.",
            evidence=["policy_check"],
        )


@pytest.mark.asyncio
async def test_prompt_injection_multi_turn_runs_until_max_turns_when_not_successful():
    scenario = PluginLoader().discover_scenarios("LLM01-Prompt Injection")["llm01.prompt_injection"]
    result = await scenario.run(
        target=TargetConfig(name="Safe Bot", url="mock://safe"),
        settings=ScanSettings(
            max_turns=5,
            prompt_injection_include_single_turn=False,
            prompt_injection_attack_types=["rag_injection"],
        ),
        target_executor=SafeTargetExecutor(),
        judge_agent=AnyJudge(),
        scan_id="test",
    )

    assert len(result.turns) == 5


@pytest.mark.asyncio
async def test_prompt_injection_multi_turn_stops_early_on_success():
    scenario = PluginLoader().discover_scenarios("LLM01-Prompt Injection")["llm01.prompt_injection"]
    result = await scenario.run(
        target=TargetConfig(name="Leaky Bot", url="mock://safe"),
        settings=ScanSettings(
            max_turns=7,
            prompt_injection_include_single_turn=False,
            prompt_injection_attack_types=["rag_injection"],
        ),
        target_executor=SuccessOnSecondTurnExecutor(),
        judge_agent=AnyJudge(),
        scan_id="test",
    )

    assert len(result.turns) == 2
